stages:
  - build-docker-images
  - test

# ==========================
#  Building Sample Projects
# ==========================
build-sp-hello-world:
  stage: build-docker-images
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./sample-projects/helloworld/
    - docker build -t shawnvosburg/helloworld .
    - docker login -u shawnvosburg -p $DOCKER_HUB_VOSS2502
    - docker push shawnvosburg/helloworld:latest

# ========================
#  Building DeployUS
# ========================
build-deployus:
  stage: build-docker-images
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./DeployUS
    - docker build -t shawnvosburg/deployus .
    - docker login -u shawnvosburg -p $DOCKER_HUB_VOSS2502
    - docker push shawnvosburg/deployus:latest


# ================================
#  Testing the created images here
# ================================
tests-deployus:
  stage: test
  image: 
    name: docker/compose:latest
    entrypoint: [""]
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
  services:
    - docker:dind
  before_script:
    - printenv
    - sh /usr/local/bin/docker-compose-entrypoint.sh
    - docker-compose -v
  script:    
    - cd DeployUS
    - docker-compose up -d 
  after_script:
    - cd DeployUS
    - docker-compose down