stages:
  - build-docker-images
  - test

# ==========================
#  Building Sample Projects
# ==========================
build-sp-hello-world:
  stage: build-docker-images
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./sample-projects/helloworld/
    - docker build -t shawnvosburg/helloworld .
    - docker login -u shawnvosburg -p $DOCKER_HUB_VOSS2502
    - docker push shawnvosburg/helloworld:latest

# ========================
#  Building DeployUS
# ========================
build-deployus:
  stage: build-docker-images
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./DeployUS
    - docker build -t shawnvosburg/deployus .
    - docker login -u shawnvosburg -p $DOCKER_HUB_VOSS2502
    - docker push shawnvosburg/deployus:latest


# ================================
#  Testing the created images here
# ================================
tests-deployus:
  stage: test
  image: 
    name: docker:stable
  services:
    - docker:dind
  before_script:
    - apk update
    - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:    
    - cd DeployUS
    - docker-compose up -d 
  after_script:
    - cd DeployUS
    - docker-compose down