version: "3.3"
services:
  app:
    build: ./
    image: shawnvosburg/watchus:latest
    ports:
      - "5001:5001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/work:/work"
