# Inspired from https://hub.docker.com/_/golang/
FROM golang:1.14-alpine

# Adding testing related dependencies
RUN apk add gcc musl-dev docker

# Copying WatchUS files
WORKDIR /go/src/app
COPY tests .

# Recommended by https://hub.docker.com/_/golang/
RUN go get -d -v ./...
RUN go install -v ./...

# Port as to which all communication will happen
CMD ["go", "test"]