version: "3.3"
services:
  app:
    build: ./
    image: shawnvosburg/watchus:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - workvolume:/work
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    image: shawnvosburg/watchustests:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - workvolume:/work

volumes:
  workvolume:
