version: "3.3"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: deployus
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
      - my-datavolume:/var/lib/mysql

  app:
    build: ./
    image: shawnvosburg/deployus:latest
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/work/scripts:/work/scripts"

volumes:
  my-datavolume: