version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: shawnvosburg/deployusdb:latest
    environment:
      MYSQL_ROOT_PASSWORD: deployus
    volumes:
      - mysql-volume:/var/lib/mysql
    networks: 
      - default
  
  workus:
    build:
      context: ../WorkUS
      dockerfile: Dockerfile
    image: shawnvosburg/workus:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks: 
      - default
      - workus-deployus

  app:
    build: ./
    image: shawnvosburg/deployus:latest
    depends_on: 
      - db
      - workus
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["/wait-for-it.sh", "db:3306", "--timeout=30","--", "python", "run.py"]
    networks: 
      - default
      - workus-deployus

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    image: deployustests
    depends_on:
      - db
      - app
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../WorkUS:/WorkUS" # Needed to kill WorkUS during persistance tests.
    command: ["/wait-for-it.sh", "app:5000", "--strict" ,"--timeout=30", "--", "pytest"]
    depends_on:
      - db
      - app
    networks: 
      - default
      - net


volumes:
  mysql-volume:

networks:
  default:

  # This one if to allow communication between a workus & deployus instance.
  workus-deployus:
  
  # This network is to connect to launched scripts during testing
  # Only the test service and the dummy script that is launched is connected to it.
  net:
    name: my_net