version: "3.3"
services:

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: deployus
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"

  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"